defaults: &defaults
    working_directory: ~/repo
    docker:
        - image: sto3psl/dw-ci:1.1.0

cache: &cache
    key: v2-dependency-cache-{{ checksum "package-lock.json" }}

version: 2
jobs:
    install:
        <<: *defaults
        steps:
            - checkout
            - restore_cache:
                  <<: *cache

            - run: npm ci

            - save_cache:
                  <<: *cache
                  paths:
                      - node_modules
                      - ~/.npm
    test:
        <<: *defaults
        steps:
            - checkout
            - restore_cache:
                  <<: *cache

            - run: npm run test

    lint:
        <<: *defaults
        steps:
            - checkout
            - restore_cache:
                  <<: *cache

            - run: npm run lint

    publish:
        <<: *defaults
        steps:
            - checkout
            - restore_cache:
                  <<: *cache

            - run:
                  name: Authenticate with registry
                  command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
            - run:
                  name: Publish Package
                  command: npm publish --access public

workflows:
    version: 2
    test and publish:
        jobs:
            - install:
                  filters:
                      tags:
                          only: /^v.*/

            - lint:
                  filters:
                      tags:
                          only: /^v.*/
                  requires:
                      - install

            - test:
                  filters:
                      tags:
                          only: /^v.*/
                  requires:
                      - install

            - publish:
                  context: Deployment Keys
                  requires:
                      - test
                      - lint
                  filters:
                      tags:
                          only: /^v.*/
                      branches:
                          ignore: /.*/
